spring:
  datasource:
    url: jdbc:mysql://localhost:3306/channelling_db
    username: channelling
    password: channelling123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true